### ISSUE TITLE
SharePath isn't a valid Parameter

### ISSUE THREAD

**Issue by commputethis** [aaronparker/LatestUpdate#11]
When using Import-LatestUpdate to import into MDT (like listed in Example 1), I am getting an error that the SharePath parameter is not valid ("A parameter cannot be found that matches parameter name 'SharePath'.  Upon further research (looking at the help file) I found that the example (both on https://docs.stealthpuppy.com/latestupdate/usage/importing-updates-into-mdt and in the help file) is incorrect and should use DeployRoot instead. 

So either the examples need updated to use DeployRoot or the parameter needs updated to be SharePath.

![capture](https://user-images.githubusercontent.com/17625274/38835691-db6b4dec-4199-11e8-9b10-3f3d7ef41e82.PNG)

**Comment by aaronparker** [comment]
Fixed in v1.1.0.36.
