### ISSUE TITLE
Using your code

### ISSUE THREAD

**Issue by pvs043** [aaronparker/LatestUpdate#13]
Hello, @aaronparker!
<p>
Can I use parts of your code in my project (https://github.com/pvs043/cMDTBuildLab)?
<p>
1. I'm really liked the design of badges in your README.md.<br>
2. I'm plan to add a script to my project for download the latest updates of Windows 10 2016 LTSB using your module.<br>
3. Most likely, it will need to make the import update function into the MDT Applications (online) instead of the Packages (offline).<br>
<p>
Thanks for your job!

**Comment by aaronparker** [comment]
Of course, go for it. You can always use `Install-Module LatestUpdate` to install the module from the PowerShell Gallery when creating your MDT share.

Also take a look at VcRedist: [https://github.com/aaronparker/Install-VisualCRedistributables](https://github.com/aaronparker/Install-VisualCRedistributables) which is also published to the PowerShell Gallery.
