### ISSUE TITLE
An exception is raised when the Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete

### ISSUE THREAD

**Issue by testworksau** [aaronparker/LatestUpdate#14]
# Expected Behavior

This script should be able to run successfully when the machine running the script has no Internet Explorer (as in Windows Server Core) or IE has not made it past the first launch wizard (as is the case when running the script under a System account, or if the user does not use IE).

# Current Behavior

An exception is raised.

# Failure Information (for bugs)

```
Invoke-WebRequest : The response content cannot be parsed because the Internet 
Explorer engine is not available, or Internet Explorer's first-launch 
configuration is not complete. Specify the UseBasicParsing parameter and try 
again. 
At C:\Program Files\WindowsPowerShell\Modules\LatestUpdate\1.1.0.38\Public\Get-
LatestUpdate.ps1:164 char:18
+         $kbID = (Invoke-WebRequest -Uri $StartKB).Content |
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupp 
   ortedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.Po 
   werShell.Commands.InvokeWebRequestCommand
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the script on a machine that hasn't had the IE first run wizard completed.
2. Alternatively, run the script on Windows Server Core
3. Alternatively, run the script on PowerShell 6 where all requests will use the equivalent of -UseBasicParsing

## Context

See the definition of UseBasicParsing here: 
https://ss64.com/ps/invoke-webrequest.html

> This parameter is required when Internet Explorer is not installed on the computers, such as on a Server Core installation of a Windows Server operating system.

And note the reference to this parameter in PowerShell 6

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6

> This parameter has been deprecated. Beginning with PowerShell 6.0.0, all Web requests use basic parsing only. This parameter is included for backwards compatibility only and any use of it will have no effect on the operation of the cmdlet.

**Comment by aaronparker** [comment]
Fixed in 72b63c0a8577f10e14d090ea4dc6732eb1c7b7cf
