### ISSUE TITLE
Doesn't return the latest update.

### ISSUE THREAD

**Issue by ILikeMonad** [aaronparker/LatestUpdate#17]
# Expected Behavior

Get-Latestupdate should return the latest update.

# Current Behavior

It returns the seconds to last update. The kB 'kb4343909'
This is the command used:
Get-LatestUpdate -WindowsVersion Windows10 -Build 17134 -Architecture x64

From the looks of it, its the link thats pulls the update infomation that doesnt't gets update.
*https://support.microsoft.com/app/content/api/content/asset/en-us/4000816*

**Comment by BladeFireLight** [comment]
having the same issue. 
did Microsoft change the URL again?

**Comment by aaronparker** [comment]
I've had a quick look at the MS page source and can't find much in the way of a new JSON feed. Some of the newer updates are listed inline in the page, so I may have to look an alternative means of sourcing the updates.

**Comment by BladeFireLight** [comment]
I was thinking the RSS Atom feed on windows support. the URL is similar but the output in in XML. 
I would be happy to fork a copy if you take pull requests.

**Comment by aaronparker** [comment]
Fixed in 72b63c0a8577f10e14d090ea4dc6732eb1c7b7cf
