### ISSUE TITLE
Windows 10 Build 17134 not returning update

### ISSUE THREAD

**Issue by Sku1ly** [aaronparker/LatestUpdate#20]
# Expected Behavior

Note of latest CU as seen here 

PS C:\Users\sgates-dadmin> Get-LatestUpdate -WindowsVersion Windows10 -Build 16299

KB        Note                                                                                        URL                                                                                                                                               
--        ----                                                                                        ---                                                                                                                                               
KB4467681 2018-11 Cumulative Update for Windows 10 Version 1709 for x64-based Systems (KB4467681)     http://download.windowsupdate.com/c/msdownload/update/software/updt/2018/11/windows10.0-kb4467681-x64_092c977b72ae27aab88c65ab31b81d3d861dda3a.msu
KB4467681 2018-11 Cumulative Update for Windows Server 2016 (1709) for x64-based Systems (KB4467681)  http://download.windowsupdate.com/c/msdownload/update/software/updt/2018/11/windows10.0-kb4467681-x64_092c977b72ae27aab88c65ab31b81d3d861dda3a.msu

# Current Behavior

No response

PS C:\Users\sgates-dadmin> Get-LatestUpdate -WindowsVersion Windows10 -Build 17134

PS C:\Users\sgates-dadmin> Get-LatestUpdate -WindowsVersion Windows10 -Build 17134
# Failure Information (for bugs)

Please help provide information about the failure if this is a bug by issuing the command using the `-Verbose` command.

```
PS C:\Users\sgates-dadmin> Get-LatestUpdate -WindowsVersion Windows10 -Build 17134 -Verbose
VERBOSE: Adding variable for dynamic parameter 'Build' with value '17134'
VERBOSE: Check updates for 17134 Cumulative.*x64
VERBOSE: Downloading https://support.microsoft.com/app/content/api/content/feeds/sap/en-us/6ae59d69-36fc-8e4d-23dd-631d98bf74a9/atom to retrieve the list of updates.
VERBOSE: GET https://support.microsoft.com/app/content/api/content/feeds/sap/en-us/6ae59d69-36fc-8e4d-23dd-631d98bf74a9/atom with 0-byte payload
VERBOSE: received -1-byte response of content type application/atom+xml; charset=utf-8
VERBOSE: Found ID: KB4467682
VERBOSE: GET http://www.catalog.update.microsoft.com/Search.aspx?q=KB4467682 with 0-byte payload
VERBOSE: received 30768-byte response of content type text/html; charset=utf-8
VERBOSE: Ids found:
VERBOSE: innerText found. Parsing KB notes```

**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Type the command Get-LatestUpdate - WindowsVersion Windows10 -Build 17134

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Tested on two machines. Server 2016 and Windows 10 1809. Other builds work.

**Comment by Sku1ly** [comment]
This is due to MS pulling the update. Sorry for bothering you

**Comment by aaronparker** [comment]
I have an update coming that will use an RSS feed that should fix this.
