### ISSUE TITLE
Get-LatestUpdate returns delta updates

### ISSUE THREAD

**Issue by ah-uk** [aaronparker/LatestUpdate#28]
# Expected Behavior

Get-LatestUpdate returns cumulative updates only 

# Current Behavior

Get-LatestUpdate returns both delta and cumulative updates which will then get downloaded and imported into MDT when automated. Think this may have started happening since January? I have to put an additional filter in place (for the word "cumulative") to avoid this as a workaround in the mean time.

**Comment by aaronparker** [comment]
I'm only seeing the cumulative update. Is this still occurring for you?

**Comment by ah-uk** [comment]
I think this issue only affects the 1st monthly cumulative and from my testing the issue is not present in [KB4487029](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4487029). I ran **Get-LatestUpdate -WindowsVersion Windows10 -Build 17134**

But if you check [KB4487017](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4487017) you will notice there are delta's in the catalogue. I'm pretty sure the feed that is used has them present and that is why I found them appearing.

Further testing would be needed on Patch Tuesday. I will try to remember to run further tests for you.

**Comment by ah-uk** [comment]
Can confirm I am correct.

PS C:\Windows\system32> Get-LatestUpdate -WindowsVersion Windows10 -Build 17134 -Verbose
VERBOSE: Checking updates for Windows10 17134.
VERBOSE: Downloading feed of updates https://support.microsoft.com/app/content/api/content/feeds/sap/en-us/6ae59d69-36fc-8e4d-23dd-631d98bf74a9/atom.
VERBOSE: GET https://support.microsoft.com/app/content/api/content/feeds/sap/en-us/6ae59d69-36fc-8e4d-23dd-631d98bf74a9/atom with 0-byte payload
VERBOSE: received -1-byte response of content type application/atom+xml; charset=utf-8
VERBOSE: Reading RSS XML from C:\Users\ASHLEY~1.ADM\AppData\Local\Temp\1htqeosp.b4x.
VERBOSE: Deleting C:\Users\ASHLEY~1.ADM\AppData\Local\Temp\1htqeosp.b4x.
VERBOSE: Found 22 items matching build 17134.
VERBOSE: Latest Windows 10 build is: 17134.648.
VERBOSE: Searching http://www.catalog.update.microsoft.com/Search.aspx?q=KB4489868.
VERBOSE: GET http://www.catalog.update.microsoft.com/Search.aspx?q=KB4489868 with 0-byte payload
VERBOSE: received 59939-byte response of content type text/html; charset=utf-8
VERBOSE: Contructing temporary table with KB, ID and URL.
VERBOSE: Checking Microsoft Update Catalog for Id: e13360f7-03eb-4341-9bb2-b526de5b1d52.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32181-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_delta_f0c8c93b9aa33310f68d5d100304a819a46d0cae.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: 3b88f267-abec-4cdf-9397-5ff8f81b1237.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32174-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-arm64_delta_ae2ead7d4e08a8f8cde3209ab4ec5a6885c003e0.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: f65ae239-c986-432c-a36c-f051eff613c0.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32166-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_delta_f0c8c93b9aa33310f68d5d100304a819a46d0cae.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: 9de58188-5319-4758-8eb1-bef0a9f3a736.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32164-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x86_delta_266eaf09438b2bff34d78fb5921550e772c59d48.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: 3f9ff099-4497-4d8f-8410-f581ca2adeca.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32162-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x86_70c1a58885238d8c7a4f581cab9e0d0aa00e5852.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: b9b03135-18e3-474e-b97e-92c5565b35d4.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32199-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_e5aaf33c58b19b162cbbbf559b9cbb5306df1a67.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: da2aaa3a-8602-49f0-b073-1a5f17eba62c.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32172-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-arm64_db280c6eb5ce7aca6abdf8a49145bba4ad0d7569.msu to output.
VERBOSE: Checking Microsoft Update Catalog for Id: 33aaf8ee-bfe9-4b24-ab07-d33a207fe74f.
VERBOSE: POST http://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 32164-byte response of content type text/html; charset=utf-8
VERBOSE: Adding http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_e5aaf33c58b19b162cbbbf559b9cbb5306df1a67.msu to output.


KB      : KB4489868
Arch    : ARM64
Version : 1803
Note    : 2019-03 Delta Update for Windows 10 Version 1803 for ARM64-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-arm64_delta_ae2ead7d4e08a8f8cde3209ab4ec5a6885c003e0.msu

KB      : KB4489868
Arch    : x64
Version : 1803
Note    : 2019-03 Delta Update for Windows 10 Version 1803 for x64-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_delta_f0c8c93b9aa33310f68d5d100304a819a46d0cae.msu

KB      : KB4489868
Arch    : x86
Version : 1803
Note    : 2019-03 Delta Update for Windows 10 Version 1803 for x86-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x86_delta_266eaf09438b2bff34d78fb5921550e772c59d48.msu

KB      : KB4489868
Arch    : x86
Version : 1803
Note    : 2019-03 Cumulative Update for Windows 10 Version 1803 for x86-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x86_70c1a58885238d8c7a4f581cab9e0d0aa00e5852.msu

KB      : KB4489868
Arch    : ARM64
Version : 1803
Note    : 2019-03 Cumulative Update for Windows 10 Version 1803 for ARM64-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-arm64_db280c6eb5ce7aca6abdf8a49145bba4ad0d7569.msu

KB      : KB4489868
Arch    : x64
Version : 1803
Note    : 2019-03 Cumulative Update for Windows 10 Version 1803 for x64-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_e5aaf33c58b19b162cbbbf559b9cbb5306df1a67.msu

KB      : KB4489868
Arch    : x64
Version : 1607
Note    : 2019-03 Delta Update for Windows Server 2016 (1803) for x64-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_delta_f0c8c93b9aa33310f68d5d100304a819a46d0cae.msu

KB      : KB4489868
Arch    : x64
Version : 1607
Note    : 2019-03 Cumulative Update for Windows Server 2016 (1803) for x64-based Systems (KB4489868)
URL     : http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/03/windows10.0-kb4489868-x64_e5aaf33c58b19b162cbbbf559b9cbb5306df1a67.msu

**Comment by aaronparker** [comment]
There's an issue with the Atom feed at the moment [https://support.microsoft.com/app/content/api/content/feeds/sap/en-au/6ae59d69-36fc-8e4d-23dd-631d98bf74a9/atom](https://support.microsoft.com/app/content/api/content/feeds/sap/en-au/6ae59d69-36fc-8e4d-23dd-631d98bf74a9/atom). It's not returning the list of updates consistently.

**Comment by aaronparker** [comment]
This should be fixed in v3 - f3e8f6ba5b754c55e6d16f452ca76fc33691d5e5
