### ISSUE TITLE
Parent folder will not be created

### ISSUE THREAD

**Issue by RyanBijkerk** [aaronparker/LatestUpdate#30]
He Aaron,

When using a path where the parent is not exciting it will end up in the catch.
For example "1902\1803". If 1902 already exists it works as expected.

https://github.com/aaronparker/LatestUpdate/blob/67f2c40443adf37c64ef8ad4d0ee65d347d1fd71/LatestUpdate/Private/New-MdtPackagesFolder.ps1#L31

**Comment by RyanBijkerk** [comment]
By the way, the -Force parameter does not work in the New-Item.
So a potential solution is to substring the path until all directories are created.

**Comment by aaronparker** [comment]
Fixed in commit 615fbab34b1ccb3097dd4dd2f3a972a6fb0c8e54

**Comment by aaronparker** [comment]
Fixed in release v2.4.0.89.
