### ISSUE TITLE
Unable to find type [System.Switch] and multiple URLs

### ISSUE THREAD

**Issue by f0nt4** [aaronparker/LatestUpdate#41]
The Save-LatestUpdate function uses the -ForceWebRequest switch, but it's incorrectly defined.

![image](https://user-images.githubusercontent.com/6190791/59028551-1d36a500-885c-11e9-92c3-e75bdc18ed8d.png)

The correct usage would be [System.Management.Automation.SwitchParameter] or simply [Switch] :)

---

Next to the switch, I found out that Microsoft thinks it's funny to add multiple URLs in an update:

![image](https://user-images.githubusercontent.com/6190791/59031697-b23d9c00-8864-11e9-9203-d77b3bb5f40b.png)

In the PR I've put the downloading part into a foreach which will make the function download every single url.

 - OS: [Windows 10]
 - PowerShell version [5.1]

**Comment by aaronparker** [comment]
Have pushed 3.0.119 to fix this
