### ISSUE TITLE
bits-transfer responsecode check

### ISSUE THREAD

**Issue by f0nt4** [aaronparker/LatestUpdate#43]
**Describe the bug**
The Save-LatestUpdate function checks if the response code is 200. Bits transfer however doesn't provide any output which makes the check always fail.
https://docs.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=win10-ps#outputs

**To Reproduce**
Simply download something using bitstransfer.
The files will be downloaded, but will still produce warnings that the response is invalid.

![image](https://user-images.githubusercontent.com/6190791/59032725-3d1f9600-8867-11e9-9b20-c8ee89f7c6ce.png)

**Comment by f0nt4** [comment]
Changing the $result = for the bits tranfer to $bitsResult and then checking if it's null or empty in the 200 check fixes the check.

```PowerShell
                            $bitsResult = Start-BitsTransfer @params
                        }
                        catch [System.Net.WebException] {
                            Write-Warning -Message ([string]::Format("Error : {0}", $_.Exception.Message))
                        }
                        catch [System.Exception] {
                            Write-Warning -Message "$($MyInvocation.MyCommand): failed to download: $URL."
                            Throw $_.Exception.Message
                        }
                    }
                }
                If (($result.StatusCode -eq "200") -or [System.String]::IsNullOrWhiteSpace($bitsResult)) {
```

**Comment by f0nt4** [comment]
Nice. Using Test-Path seems like a reasonable test to determine if the download was successful. You might want to add `-ErrorAction SilentlyContinue` to prevent output of an error though.

**Comment by aaronparker** [comment]
Have pushed 3.0.119 to fix this
