### ISSUE TITLE
Version param not honored

### ISSUE THREAD

**Issue by f0nt4** [aaronparker/LatestUpdate#44]
**Describe the bug**
The Get-LatestAdobeFlashUpdate and Get-LatestNetFrameworkUpdate functions don't filter the results for the correct version.
And as you can see in the 3rd item in the list if an entry does not have a version number, it picks the OS.

**To Reproduce**

![image](https://user-images.githubusercontent.com/6190791/59041832-b1633500-8879-11e9-98b2-3ade0f0bf417.png)

**Comment by f0nt4** [comment]
I'm thinking that it might be for the best that the param is not honorred, because in my use case, for Server 2019 or Server 2016, there's no version in the Note. In this case, I'd rather just get all the available updates and pick out the one I need manually.

**Comment by aaronparker** [comment]
I was thinking of adding support for `-Version` in the future, but the less parameters I need to deal with the less testing and code required.

**Comment by f0nt4** [comment]
`-Version` support would be nice, but I think it will be quite difficult to get it working for all OS-es as not every Note had the version in it.
That way, you'd have to make it an optional parameter nevertheless.

**Comment by BladeFireLight** [comment]
the problem with a -version is the validation set's do not always get updated in a timely manner, if you keep -version remove the validation set.
I would prefer to just use |where version -eq 1903

**Comment by aaronparker** [comment]
Removed Version parameter in 3.0.119

**Comment by f0nt4** [comment]
The Get-LatestNetFrameworkUpdate currently doesn't return the latest updates for Windows 7, 8 or Server 2012 which probably is because the searchstring includes "Cumulative" while for 2012 it's something like "Security and Quality Rollup".
Personally I don't mind this as we stopped patching the 2012 images and simply advertise to 2012 installations, but others might want to download them.

**Comment by aaronparker** [comment]
I've only been looking at this for Windows 10 / Windows Server 2016 etc. at this point. I can add support for legacy versions in a later update

**Comment by f0nt4** [comment]
I found a way to quite easily get the results for other OS's. I've added that solution to my PR.
