### ISSUE TITLE
Latest Flash not returning server updates

### ISSUE THREAD

**Issue by f0nt4** [aaronparker/LatestUpdate#51]
Hi Aaron,

Something seems to be off with `Get-LatestAdobeFlashUpdate`. No matter which arguments I provide, it doesn't seem to return the latest flash update for Windows Server 2016/2019.

Here it doesn't return the latest flash update for Windows Server 2019.

![image](https://user-images.githubusercontent.com/6190791/62037281-cb732100-b1f3-11e9-92ad-b430995cad8c.png)

It also seems to return duplicate entries for build 1607 and also here the update for Server 2016 is missing.

![image](https://user-images.githubusercontent.com/6190791/62037385-fe1d1980-b1f3-11e9-8524-e6d94668f6ce.png)

**Comment by aaronparker** [comment]
If you run this with `-Verbose`, you'll see that it builds a search query for the Catalog: [https://www.catalog.update.microsoft.com/Search.aspx?q=KB4503308+1809](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4503308+1809). From the feed this is the latest update. The catalog doesn't return any updates with Windows Server 2019 in the title.

Even a search for "[adobe flash 1809](https://www.catalog.update.microsoft.com/Search.aspx?q=adobe+flash+1809) doesn't return Windows Server 2019 updates either. Searching for "2016" or "2019" does return updates.

Windows 10 x64 updates are applicable to Windows Server 2019 of course. I don't really want to add code just for 2016/2019 when the Windows 10 x64 updates apply.

**Comment by f0nt4** [comment]
It does return results with "Windows Server 2019" in the name:
![image](https://user-images.githubusercontent.com/6190791/62410914-d57a9280-b5ec-11e9-9623-880a2e0ca4af.png)

Also searching for the latest KB returns the windows server 2016/2019 etc wanted results:
![image](https://user-images.githubusercontent.com/6190791/62410924-107cc600-b5ed-11e9-8ea2-c6534c55cbc5.png)

Before your changes, it did return these results. So currently the function is returning incomplete/incorrect results.
Using it like `-OS Windows10 -Version 1809` does not return the wanted results anymore.

**Comment by f0nt4** [comment]
Thanks for merging my PR. I was just thinking that it might be an idea to make the default fallback on PSCore to webclient as downloading is faster than using WebRequest as you can see in the screenshot underneath:
![image](https://user-images.githubusercontent.com/6190791/63637114-e6ad4100-c678-11e9-93bb-91588ce5f7c9.png)

Also in Powershell 5, the difference is a lot bigger:
![image](https://user-images.githubusercontent.com/6190791/63637612-743f5f80-c67e-11e9-9556-a89fe1046fcb.png)

These test result are produced by the following small script: https://pastebin.com/0iksKb0w

**Comment by aaronparker** [comment]
I might look at using WebClient the default for all requests in the release after next. Querying the catalog could be faster and WebClient might help.

**Comment by f0nt4** [comment]
That would be best I guess. Would also help with implementing proxy support.
